# --- !Ups

create table SCHEME (
    EMPREF VARCHAR NOT NULL PRIMARY KEY,
    TERMINATION_DATE DATE NULL
);

CREATE TABLE LEVY_DECLARATION(
  YEAR INTEGER NOT NULL,
  MONTH INTEGER NOT NULL,
  AMOUNT NUMERIC NOT NULL,
  EMPREF VARCHAR NOT NULL,
  PRIMARY KEY (YEAR, MONTH, EMPREF),
  FOREIGN KEY (EMPREF) REFERENCES SCHEME(EMPREF)
);




# --- !Downs

DROP TABLE LEVY_DECLARATION;
DROP TABLE "SCHEME";
