# --- !Ups


CREATE TABLE GATEWAY_USER (
  ID       INTEGER NOT NULL PRIMARY KEY,
  USERNAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL
);

CREATE TABLE GATEWAY_ENROLMENT (
  GATEWAY_USER_ID INTEGER NOT NULL REFERENCES GATEWAY_USER,
  EMPREF          VARCHAR NOT NULL REFERENCES SCHEME
);

INSERT INTO GATEWAY_USER (ID, USERNAME, PASSWORD) VALUES (1, 'gateway1', 'password');
INSERT INTO GATEWAY_USER (ID, USERNAME, PASSWORD) VALUES (2, 'gateway2', 'password');

INSERT INTO GATEWAY_ENROLMENT (GATEWAY_USER_ID, EMPREF) VALUES (1, '123/AB12345');
INSERT INTO GATEWAY_ENROLMENT (GATEWAY_USER_ID, EMPREF) VALUES (1, '123/BC12345');
INSERT INTO GATEWAY_ENROLMENT (GATEWAY_USER_ID, EMPREF) VALUES (1, '321/ZX54321');
INSERT INTO GATEWAY_ENROLMENT (GATEWAY_USER_ID, EMPREF) VALUES (2, '222/MM22222');


# --- !Downs

DELETE FROM GATEWAY_ENROLMENT;
DELETE FROM GATEWAY_USER;

DROP TABLE GATEWAY_ENROLMENT;
DROP TABLE GATEWAY_USER;